const FETCH_USER =  "FETCH_USER";
const INIT_USER = "INIT_USER";
const UPDATE_USER =  "UPDATE_USER";
const FETCH_IMAGE =  "FETCH_IMAGE";
const UPDATE_IMAGE =  "UPDATE_IMAGE";
const UPDATE_PAGI =  "UPDATE_PAGI";
const UPDATE_FILTER_DATE = "UPDATE_FILTER_DATE";
const UPDATE_FILTER_RANGE =  "UPDATE_FILTER_RANGE";
const FETCH_VIDEO = "FETCH_VIDEO";
const UPDATE_VIDEO = "UPDATE_VIDEO";
const LOCK_USER =  "LOCK_USER";
const LOCK_WEB =  "LOCK_WEB";
const GET_USER =  "GET_USER";
export {
    INIT_USER,
    FETCH_USER,
    UPDATE_USER,
    FETCH_IMAGE,
    UPDATE_IMAGE,
    UPDATE_FILTER_DATE,
    UPDATE_PAGI,
    UPDATE_FILTER_RANGE,
    FETCH_VIDEO,
    UPDATE_VIDEO,
    LOCK_USER,
    LOCK_WEB,
    GET_USER
}